services:
  app:
    image: ghcr.io/breezybuddy69/jayden-portfolio:main
    container_name: jayden-portfolio-app
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jayden-portfolio.rule=Host(`jayden-mikus.halovisionai.cloud`)"
      - "traefik.http.routers.jayden-portfolio.entrypoints=websecure"
      - "traefik.http.routers.jayden-portfolio.tls=true"
      - "traefik.http.routers.jayden-portfolio.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.services.jayden-portfolio.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true
