version: "3.9"

services:
  app:
    build: .
    container_name: jayden-portfolio-app
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.jayden.rule=Host(`jayden-mikus.halovisionai.cloud`)
      - traefik.http.routers.jayden.entrypoints=websecure
      - traefik.http.routers.jayden.tls=true
      - traefik.http.routers.jayden.tls.certresolver=letsencrypt
      - traefik.http.services.jayden.loadbalancer.server.port=80

networks:
  traefik-proxy:
    external: true
